"""baseline: full schema as of v57

Revision ID: 66b672165732
Revises: 
Create Date: 2026-09-08 09:20:43.563353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b672165732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pujan_year', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.String(length=50), nullable=True),
    sa.Column('report_time', sa.String(length=50), nullable=True),
    sa.Column('ho_venue', sa.String(length=200), nullable=True),
    sa.Column('ho_address', sa.Text(), nullable=True),
    sa.Column('center_venue', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('samagri_gu', sa.Text(), nullable=True),
    sa.Column('samagri_en', sa.Text(), nullable=True),
    sa.Column('body_center_gu', sa.Text(), nullable=True),
    sa.Column('body_center_en', sa.Text(), nullable=True),
    sa.Column('body_ho_gu', sa.Text(), nullable=True),
    sa.Column('body_ho_en', sa.Text(), nullable=True),
    sa.Column('subject_gu', sa.String(length=200), nullable=True),
    sa.Column('subject_en', sa.String(length=200), nullable=True),
    sa.Column('poster_data', sa.LargeBinary(), nullable=True),
    sa.Column('poster_mime', sa.String(length=80), nullable=True),
    sa.Column('poster_name', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pujan_year')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_gu', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_gu', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('role_keys', sa.Text(), nullable=True),
    sa.Column('any_perms', sa.Text(), nullable=True),
    sa.Column('all_perms', sa.Text(), nullable=True),
    sa.Column('require_accept', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('pujan_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_gu', sa.String(length=150), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('include_poster', sa.Boolean(), nullable=True),
    sa.Column('pujan_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_gu', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('center_scoped', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_label', sa.String(length=300), nullable=True),
    sa.Column('pujan_year', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_pujan_year'), ['pujan_year'], unique=False)

    op.create_table('instruction_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instruction_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instruction_id', 'version', name='uq_accept_user_instruction_version')
    )
    op.create_table('manuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_gu', sa.String(length=200), nullable=True),
    sa.Column('about', sa.String(length=400), nullable=True),
    sa.Column('about_gu', sa.String(length=400), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('role_keys', sa.Text(), nullable=True),
    sa.Column('any_perms', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('member_code', sa.String(length=50), nullable=True),
    sa.Column('member_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('firm_name', sa.String(length=200), nullable=True),
    sa.Column('firm_address', sa.Text(), nullable=True),
    sa.Column('firm_contact', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_contact', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('event_registered_year', sa.Integer(), nullable=True),
    sa.Column('dharmada_type', sa.String(length=10), nullable=True),
    sa.Column('dharmada_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('attend_at_ho', sa.Boolean(), nullable=False),
    sa.Column('ho_year', sa.Integer(), nullable=True),
    sa.Column('ho_marked_by', sa.Integer(), nullable=True),
    sa.Column('ho_marked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['ho_marked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_member_code'), ['member_code'], unique=True)

    op.create_table('pass_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pujan_year', sa.Integer(), nullable=False),
    sa.Column('yajman_start', sa.Integer(), nullable=True),
    sa.Column('guruji_start', sa.Integer(), nullable=True),
    sa.Column('general_start', sa.Integer(), nullable=True),
    sa.Column('yajman_prefix', sa.String(length=10), nullable=True),
    sa.Column('guruji_prefix', sa.String(length=10), nullable=True),
    sa.Column('general_prefix', sa.String(length=10), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pujan_year')
    )
    op.create_table('scheduled_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('years', sa.Text(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('comm_type', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('pujan_year', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entity_member_type', ['member_id', 'entity_type'], unique=False)

    op.create_table('entity_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('member_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_persons_member_code'), ['member_code'], unique=False)

    op.create_table('firm_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pujan_year', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('firm_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pujan_year', 'entity_id', name='uq_firmno_entity_year'),
    sa.UniqueConstraint('pujan_year', 'firm_no', name='uq_firmno_year')
    )
    with op.batch_alter_table('firm_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_numbers_pujan_year'), ['pujan_year'], unique=False)

    op.create_table('sankalps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('pujan_year', sa.Integer(), nullable=False),
    sa.Column('sankalp_type', sa.String(length=50), nullable=False),
    sa.Column('sankalp_name', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('owner_center_id', sa.Integer(), nullable=True),
    sa.Column('carried_from_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carried_from_id'], ['sankalps.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['owner_center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['entity_persons.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sankalp_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sankalp_id'], ['sankalps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('sankalp_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('pujan_year', sa.Integer(), nullable=False),
    sa.Column('pass_number', sa.String(length=50), nullable=False),
    sa.Column('pass_type', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=True),
    sa.Column('last_printed_at', sa.DateTime(), nullable=True),
    sa.Column('last_printed_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_printed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['sankalp_id'], ['sankalps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pujan_year', 'pass_number', name='uq_pass_year_number')
    )
    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.create_index('ix_pass_year_type', ['pujan_year', 'pass_type'], unique=False)

    op.create_table('sankalp_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sankalp_id', sa.Integer(), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sankalp_id'], ['sankalps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('pujan_year', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.Column('slip_printed_at', sa.DateTime(), nullable=True),
    sa.Column('slip_printed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ),
    sa.ForeignKeyConstraint(['slip_printed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'pujan_year', name='uq_attendance_member_year'),
    sa.UniqueConstraint('pujan_year', 'seat_no', name='uq_attendance_seat_year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('sankalp_changes')
    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.drop_index('ix_pass_year_type')

    op.drop_table('passes')
    op.drop_table('collections')
    op.drop_table('sankalps')
    with op.batch_alter_table('firm_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_numbers_pujan_year'))

    op.drop_table('firm_numbers')
    with op.batch_alter_table('entity_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_persons_member_code'))

    op.drop_table('entity_persons')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_member_type')

    op.drop_table('entities')
    op.drop_table('comm_logs')
    op.drop_table('scheduled_messages')
    op.drop_table('pass_config')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_member_code'))

    op.drop_table('members')
    op.drop_table('manuals')
    op.drop_table('instruction_acceptances')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_pujan_year'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_key'))

    op.drop_table('roles')
    op.drop_table('message_templates')
    op.drop_table('instructions')
    op.drop_table('event_config')
    op.drop_table('centers')
    # ### end Alembic commands ###
